local cmdDescs = {
    {name = "!AntiFall", desc = "Prevents your character from falling"},
    {name = "!AntiSeat", desc = "Prevents automatic seating when clicking vehicles"},
    {name = "!UnAntiSeat", desc = "Disables the AntiSeat feature"},
    {name = "!Bring All Horse", desc = "Teleports all horses to your location"},
    {name = "!Bye Bye [Leave the Server]", desc = "Leaves the current server"},
    {name = "!Car Duke", desc = "Activates car duke animation once"},
    {name = "!Auto Car Duke", desc = "Continuously activates car duke animation"},
    {name = "!UnAuto Car Duke", desc = "Stops automatic car duke animation"},
    {name = "!Auto Spam Vehicle", desc = "Continuously spawns vehicles"},
    {name = "!UnAuto Spam Vehicle", desc = "Stops automatic vehicle spawning"},
    {name = "!Chat Spy Selected Plr Gui", desc = "Shows a GUI to spy on selected player's chat"},
    {name = "!Chat Draw Gui", desc = "Opens a GUI for drawing in chat"},
    {name = "!C Roblox has joined the game", desc = "Sends fake Roblox join message in chat"},
    {name = "!Clear The Chat", desc = "Clears the chat history"},
    {name = "!Art Heart In The Chat", desc = "Displays a heart ASCII art in chat"},
    {name = "!Art Up Arrow", desc = "Displays an up arrow ASCII art in chat"},
    {name = "!Art Down Arrow", desc = "Displays a down arrow ASCII art in chat"},
    {name = "!Fake Error", desc = "Displays a fake error message"},
    {name = "!Fake Ban", desc = "Displays a fake ban message"},
    {name = "!Art GG", desc = "Displays 'GG' ASCII art in chat"},
    {name = "!Art Winning", desc = "Displays 'WINNING' ASCII art in chat"},
    {name = "!Auto Curtains House", desc = "Automatically toggles house curtains"},
    {name = "!UnAuto Curtains House", desc = "Stops automatic curtain toggling"},
    {name = "!House Curtains", desc = "Toggles house curtains once"},
    {name = "!Delete All Vehicles", desc = "Removes all vehicles from the map"},
    {name = "! Destroy Tools that Make Lag", desc = "Destroys lag-causing tools"},
    {name = "!Destroy Car Wheel 1", desc = "Destroys first wheel of targeted car"},
    {name = "!Destroy Car Wheel 2", desc = "Destroys second wheel of targeted car"},
    {name = "!Destroy Car Wheel 3", desc = "Destroys third wheel of targeted car"},
    {name = "!Destroy Car Wheel 4", desc = "Destroys fourth wheel of targeted car"},
    {name = "!Destroy All Car Wheel", desc = "Destroys all wheels of targeted car"},
    {name = "!Remove House Ban", desc = "Removes house ban once"},
    {name = "!Auto Remive House Ban", desc = "Continuously removes house bans"},
    {name = "!UnAuto Remove House Ban", desc = "Stops automatic house ban removal"},
    {name = "!Auto Fire Car", desc = "Continuously sets cars on fire"},
    {name = "!UnAuto Fire Car", desc = "Stops automatic car fire"},
    {name = "!Fire Car", desc = "Sets targeted car on fire once"},
    {name = "!Fire House", desc = "Sets house on fire once"},
    {name = "!Auto Fire House", desc = "Continuously sets houses on fire"},
    {name = "!UnAuto Fire House", desc = "Stops automatic house fire"},
    {name = "!Auto House Garage Door", desc = "Automatically toggles garage doors"},
    {name = "!UnAuto House Garage Door", desc = "Stops automatic garage door toggling"},
    {name = "!House Garage Door", desc = "Toggles house garage door once"},
    {name = "!Auto Car Hazard", desc = "Automatically toggles car hazard lights"},
    {name = "!UnAuto Car Hazard", desc = "Stops automatic hazard light toggling"},
    {name = "!Car Hazard", desc = "Toggles car hazard lights once"},
    {name = "!Auto Car Horn", desc = "Automatically honks car horn"},
    {name = "!UnAuto Car Horn", desc = "Stops automatic car horn"},
    {name = "!Car Horn", desc = "Honks car horn once"},
    {name = "!Auto Car Light", desc = "Automatically toggles car lights"},
    {name = "!UnAuto Car Light", desc = "Stops automatic car light toggling"},
    {name = "!Car Light", desc = "Toggles car lights once"},
    {name = "!Auto Lock House Door", desc = "Automatically locks house doors"},
    {name = "!UnAuto Lock House Door", desc = "Stops automatic door locking"},
    {name = "!Lock House Door", desc = "Locks house doors once"},
    {name = "!Auto House Pool", desc = "Automatically toggles house pool"},
    {name = "!UnAuto House Pool", desc = "Stops automatic pool toggling"},
    {name = "!House Pool", desc = "Toggles house pool once"},
    {name = "!Spawn Skite Board", desc = "Spawns a skateboard"},
    {name = "!Remove Skite Board", desc = "Removes spawned skateboard"},
    {name = "!Horse Slice", desc = "Slices nearby horses"},
    {name = "!Auto Car Smoke", desc = "Automatically toggles car smoke"},
    {name = "!UnAuto Car Smoke", desc = "Stops automatic car smoke toggling"},
    {name = "!Car Smoke", desc = "Toggles car smoke once"},
    {name = "!Couch Seat Fling", desc = "Flings players using couch seats"},
    {name = "!Tp to Spawn", desc = "Teleports to spawn location"},
    {name = "!Tp To Water", desc = "Teleports to water area"},
    {name = "!Tp To Void", desc = "Teleports to void area"},
    {name = "!Tp To School", desc = "Teleports to school location"},
    {name = "!Tp To mountains", desc = "Teleports to mountains area"},
    {name = "!Tp To Road", desc = "Teleports to road area"},
    {name = "!Player Tp Click", desc = "Teleports to clicked player"},
    {name = "!Enable Trail", desc = "Enables character trail effect"},
    {name = "!Disable Trail", desc = "Disables character trail effect"},
    {name = "!Walk On Void", desc = "Allows walking on void areas"},
    {name = "!Sell Your House", desc = "Sells your current house"},
    {name = "!UnFire House", desc = "Extinguishes house fire"},
    {name = "!UnAntiFall", desc = "Disables anti-fall feature"},
    {name = "!Hug Nearest", desc = "Hugs nearest player"},
    {name = "!Goku Tp", desc = "Teleports like Goku instant transmission"},
    {name = "!Chat Logs", desc = "Shows chat logs GUI"},
    {name = "!Turn back time", desc = "Reverts logs to previous state"},
    {name = "!Super Man Fly", desc = "Enables Superman flying mode"},
    {name = "!Shift Lock", desc = "Toggles shift lock mode"},
    {name = "!Walk On Air", desc = "Allows walking on air"},
    {name = "!Chat Bypass En", desc = "Enables chat filter bypass"},
    {name = "!Trip LP", desc = "Makes local player trip"},
    {name = "!Sky PL", desc = "Drives in the sky"},
    {name = "!Walk On Void", desc = "Allows walking on void"},
    {name = "!AntiVoid", desc = "Prevents falling into void"},
    {name = "!Free Cam", desc = "Enables free camera mode"},
    {name = "!Fe BoomBox", desc = "Spawns FE boombox tool"},
    {name = "!Couch Flinger", desc = "Flings players using couch tool"},
    {name = "!Ronaldo Mod", desc = "Activates Ronaldo mode"},
    {name = "!Spam Basket ball", desc = "Spams basketball tool"},
    {name = "!Spam Bomb", desc = "Spams bomb tool"},
    {name = "!Light Spawn", desc = "Spawns highlight effect"},
    {name = "!Small Dick", desc = "Creates small inappropriate shape"},
    {name = "!Medium Dick", desc = "Creates medium inappropriate shape"},
    {name = "!Big Dick", desc = "Creates large inappropriate shape"},
    {name = "!Long Dick", desc = "Creates extended inappropriate shape"},
    {name = "!Long Couch", desc = "Creates extended couch"},
    {name = "!Couch Sword", desc = "Creates sword using couch tool"},
    {name = "!Long FireX", desc = "Creates extended fire extinguisher"},
    {name = "!Long Box", desc = "Creates extended box"},
    {name = "!sq Light", desc = "Creates square light effect"},
    {name = "!Sq Red", desc = "Creates red square effect"},
    {name = "!Sq Black", desc = "Creates black square effect"},
    {name = "!FireX Nazi", desc = "Creates offensive symbol with fire extinguisher"},
    {name = "!2025 Basketball", desc = "Creates 2025 basketball effect"},
    {name = "!2025 FireX", desc = "Creates 2025 fire extinguisher effect"},
    {name = "!2025 Paperbag Fire", desc = "Creates 2025 paperbag fire effect"},
    {name = "!2025 Bomb", desc = "Creates 2025 bomb effect"},
    {name = "!WateringCan Floor", desc = "Creates floor effect with watering can"},
    {name = "!Small Tree", desc = "Creates small tree"},
    {name = "!Giant Tree", desc = "Creates giant tree"},
    {name = "!Big Tree", desc = "Creates big tree"},
    {name = "!Small SWATShield Wall", desc = "Creates small wall with SWAT shield"},
    {name = "!Mid SWATShield Wall", desc = "Creates medium wall with SWAT shield"},
    {name = "!Giant SWATShield Wall", desc = "Creates giant wall with SWAT shield"},
    {name = "!Snow Gun", desc = "Creates snow gun effect"},
    {name = "!Sign Tower", desc = "Creates tower with sign tool"},
    {name = "!Sign Pyramid", desc = "Creates pyramid with sign tool"},
    {name = "!Paint Roller Sky", desc = "Creates sky effect with paint roller"},
    {name = "!Nazi Assault", desc = "Creates offensive symbol with assault tool"},
    {name = "!Nazi Snow Gun", desc = "Creates offensive symbol with snow gun"},
    {name = "!Nazi Present", desc = "Creates offensive symbol with present tool"},
    {name = "!Umbrella Nazi", desc = "Creates offensive symbol with umbrella"},
    {name = "!Giant JoustRed Nazi", desc = "Creates offensive symbol with red joust tool"},
    {name = "!JoustRed Dick", desc = "Creates inappropriate shape with red joust tool"},
    {name = "!JoustBlue Dick", desc = "Creates inappropriate shape with blue joust tool"},
    {name = "!HotDog Soviet", desc = "Creates symbol with hotdog tool"},
    {name = "!high beams", desc = "Creates high beam light effect"},
    {name = "!Idk Forget But Its FireX", desc = "Creates unknown effect with fire extinguisher"},
    {name = "!Bomb Soviet", desc = "Creates symbol with bomb tool"},
    {name = "!Giant Nigg#er Text", desc = "Creates offensive text"},
    {name = "!Auto Rainbow Rp Name", desc = "Makes roleplay name cycle through rainbow colors"},
    {name = "!UnAuto Rainbow Rp Name", desc = "Stops rainbow roleplay name effect"},
    {name = "!Auto Rainbow Rp Bio", desc = "Makes roleplay bio cycle through rainbow colors"},
    {name = "!UnAuto Rainbow Rp Bio", desc = "Stops rainbow roleplay bio effect"},
    {name = "!Auto Rainbow Vehicle", desc = "Makes vehicle cycle through rainbow colors"},
    {name = "!UnAuto Rainbow Vehicle", desc = "Stops rainbow vehicle effect"},
    {name = "!Auto Rainbow Hair", desc = "Makes hair cycle through rainbow colors"},
    {name = "!UnAuto Rainbow Hair", desc = "Stops rainbow hair effect"},
    {name = "!Remove Emmiter", desc = "Removes particle emitters"},
    {name = "!Get All Tools [Beta]", desc = "Attempts to get all available tools"},
    {name = "!Sq Spray Can", desc = "Creates square with spray can tool"},
    {name = "!Purple Fire", desc = "Creates purple fire effect"},
    {name = "!Black Fire", desc = "Creates black fire effect"},
    {name = "!Orange Fire", desc = "Creates orange fire effect"},
    {name = "!Blue Fire", desc = "Creates blue fire effect"},
    {name = "!White Fire", desc = "Creates white fire effect"},
    {name = "!Green Fire", desc = "Creates green fire effect"},
    {name = "!Auto ColorFul Fire", desc = "Makes fire cycle through colors"},
    {name = "!UnAuto ColorFul Fire", desc = "Stops colorful fire effect"},
    {name = "!Fire Local Plr", desc = "Sets local player on fire"},
    {name = "!Smoke Local Plr", desc = "Creates smoke effect on local player"},
    {name = "!Car Race Mode", desc = "Activates racing mode for cars"},
    {name = "!Bring All Vehicles", desc = "Teleports all vehicles to your location"},
    {name = "!Save Your Pos", desc = "Saves your current position"},
    {name = "! Teleport To saved Pos", desc = "Teleports to previously saved position"},
    {name = "!Airport alarm activation", desc = "Activates airport alarm system"},
    {name = "!Shutdown The Server", desc = "Attempts to shutdown the server"},
    {name = "!Fast Hold all tools", desc = "Quickly holds all tools"},
    {name = "! Normal Hold all tools", desc = "Holds all tools at normal speed"},
    {name = "!Fas UnHold all tools", desc = "Quickly unholds all tools"},
    {name = "!Normal UnHold all tools", desc = "Unholds all tools at normal speed"},
    {name = "!Remove all Props", desc = "Removes all props in the game"},
    {name = "!Auto Colorful Weapon", desc = "Makes weapons cycle through colors"},
    {name = "!UnAuto Colorful Weapon", desc = "Stops colorful weapon effect"},
    {name = "!Auto Colorful Spray", desc = "Makes spray paint cycle through colors"},
    {name = "!UnAuto Colorful Spray", desc = "Stops colorful spray effect"},
    {name = "!Anti Fling University", desc = "Prevents being flung at university area"},
    {name = "!Anti Kick [Idk]", desc = "Attempts to prevent being kicked"},
    {name = "!Fix Cam if Buged", desc = "Fixes camera if bugged"},
    {name = "!Anim Logger", desc = "Logs animations played by players"},
    {name = "!Dex [Lol]", desc = "Opens Dex explorer"},
    {name = "!Anti Vehicle Fling", desc = "Prevents being flung by vehicles"},
    {name = "!Baby Spin", desc = "Makes babies spin"},
    {name = "!Couch Seat Killer", desc = "Kills players using couch seats"},
    {name = "!Vehicle Seat Killer", desc = "Kills players in vehicle seats"},
    {name = "!Auto Change Size", desc = "Automatically changes character size"},
    {name = "!UnAuto Change Size", desc = "Stops automatic size changing"},
    {name = "!Auto Spray", desc = "Automatically uses spray paint"},
    {name = "!UnAuto Spray", desc = "Stops automatic spray painting"}
}
